/**
 * China Explorer — Centralized Trip Data
 * Single source of truth for all trip information.
 * Coordinates, dates, activities, budget, packing items.
 */
const TRIP = {
  name: 'China Explorer',
  subtitle: 'A Journey Through China',
  author: 'CC & Joseph',
  arrival: '2026-12-06',
  departure: '2027-01-11',
  thailand: { start: '2026-12-24', end: '2026-12-30' },
  split: 'Dec 24 eve — A→Dalian / B→Thailand, reunite Dec 30 in Beijing',

  cities: [
    {
      id: 'shenzhen',
      name: 'Shenzhen · 深圳',
      emoji: '🏙️',
      coords: [22.5431, 114.0579],
      startDate: '2026-12-06',
      endDate: '2026-12-12',
      nights: 7,
      tags: ['Modern', 'Coastal', { label: 'Warm Winter', cls: 'green' }],
      image: 'https://images.unsplash.com/photo-1522614288668-a697127e9b21?w=800&q=80',
      weather: { temp: '15–22°C', season: 'Early Winter · Dec', icon: '🌤️' },
      transport: { from: 'Hong Kong (arrival)', mode: '🛬', duration: null },
      activities: [
        'Window of the World park',
        'OCT Harbour & Creative Culture Park',
        'Dapeng Fortress day trip',
        'Seafood dinner at Shekou',
        'Lianhua Mountain Park',
      ],
      notes: 'Kick off in Shenzhen — mild winter, great food, and a perfect jet-lag recovery spot.',
    },
    {
      id: 'wangxian',
      name: 'Wangxian Valley · 望仙谷',
      emoji: '🏞️',
      coords: [28.4547, 117.9783],
      startDate: '2026-12-13',
      endDate: '2026-12-14',
      nights: 2,
      tags: [{ label: 'Nature', cls: 'green' }, 'Hiking', 'Photography'],
      image: 'https://images.unsplash.com/photo-1546881963-ac8d67aee789?w=800&q=80',
      weather: { temp: '5–12°C', season: 'Winter · Dec', icon: '🌤️' },
      transport: { from: 'Shenzhen', mode: '✈️', duration: '~2h' },
      activities: [
        'Valley scenic hiking trails',
        'Viewpoint photography',
        'Local village exploration',
        'Stargazing at night',
        'Fresh mountain cuisine',
      ],
      notes: 'A quick nature escape into the stunning cliffside village.',
    },
    {
      id: 'chongqing',
      name: 'Chongqing · 重庆',
      emoji: '⛰️',
      coords: [29.4316, 106.9123],
      startDate: '2026-12-15',
      endDate: '2026-12-19',
      nights: 5,
      tags: ['Mountain', { label: 'Spicy Food', cls: 'amber' }, 'River Views'],
      image: 'https://images.unsplash.com/photo-1779428261059-a43781b23e54?w=800&q=80',
      weather: { temp: '7–12°C', season: 'Winter · Dec', icon: '🌫️' },
      transport: { from: 'Wangxian Valley', mode: '🚌', duration: '~3h' },
      activities: [
        'Yangtze River cable car',
        'Hongya Cave night view',
        'Ci Qi Kou old town',
        'Chongqing hotpot dinner',
        'River cruise at night',
      ],
      notes: 'Sichuan\u2019s spicy heart. Hotpot warms you right up in winter.',
    },
    {
      id: 'chengdu',
      name: 'Chengdu · 成都',
      emoji: '🐼',
      coords: [30.5728, 104.0668],
      startDate: '2026-12-19',
      endDate: '2026-12-24',
      nights: 5,
      tags: [{ label: 'Pandas', cls: 'green' }, 'Tea Culture', { label: 'Food', cls: 'amber' }],
      image: 'https://images.unsplash.com/photo-1625859043880-56acbcb6a6ac?w=800&q=80',
      weather: { temp: '3–10°C', season: 'Winter · Dec', icon: '🌦️' },
      transport: { from: 'Chongqing', mode: '🚄', duration: '~3h' },
      activities: [
        'Giant Panda Breeding Base',
        'Jinli Ancient Street & tea houses',
        'Sichuan hotpot & street food',
        'Wuhou Shrine & Jinli',
        'People\'s Park & local life',
      ],
      notes: 'Pandas, tea houses, and the best Sichuan food — a perfect 5-day wrap.',
    },
    {
      id: 'dalian',
      name: 'Dalian · 大连 (A)',
      emoji: '🌊',
      coords: [38.9140, 121.6147],
      startDate: '2026-12-24',
      endDate: '2026-12-30',
      nights: 6,
      tags: [{ label: 'Coastal', cls: 'green' }, 'Seafood', 'Quiet'],
      image: 'https://images.unsplash.com/photo-1694722050574-d483e44eaf2b?w=800&q=80',
      weather: { temp: '-5–2°C', season: 'Winter · Dec', icon: '❄️' },
      transport: { from: 'Chengdu (split)', mode: '✈️', duration: '~3h' },
      activities: [
        'Xinghai Square & seaside walk',
        'Binhai Road scenic drive',
        'Russian Style Street',
        'Fresh seafood dinner',
        'Discoveryland theme park',
      ],
      notes: 'Person A heads north to Dalian for a quiet week by the frozen coast.',
    },
    {
      id: 'thailand-leg',
      name: 'Thailand (B)',
      emoji: '🇹🇭',
      coords: [13.7563, 100.5018],
      startDate: '2026-12-24',
      endDate: '2026-12-30',
      nights: 6,
      tags: ['Beaches', 'Temples', { label: 'Tropical', cls: 'green' }],
      weather: { temp: '25–32°C', season: 'Winter · Dec', icon: '☀️' },
      transport: { from: 'Chengdu (split)', mode: '✈️', duration: '~3h' },
      activities: [
        'Grand Palace & Wat Phra Kaew',
        'Chatuchak Weekend Market',
        'Street food tour',
        'Day trip to Ayutthaya',
        'Floating market experience',
      ],
      notes: 'Person B escapes to Thailand for sun, temples, and incredible street food.',
      image: 'https://images.unsplash.com/photo-1655815917186-76a5e56b58d5?w=800&q=80',
    },
    {
      id: 'beijing',
      name: 'Beijing · 北京',
      emoji: '🏛️',
      coords: [39.9042, 116.4074],
      startDate: '2026-12-30',
      endDate: '2027-01-03',
      nights: 4,
      tags: ['History', 'Landmarks', { label: 'Reunion', cls: 'amber' }],
      image: 'https://images.unsplash.com/photo-1663859454065-0b5650775708?w=800&q=80',
      weather: { temp: '-8–2°C', season: 'Winter · Jan', icon: '❄️' },
      transport: { from: 'Dalian / Thailand (reunite)', mode: '✈️', duration: null },
      activities: [
        'Forbidden City & Tiananmen Square',
        'Great Wall (Mutianyu section)',
        'Temple of Heaven & Summer Palace',
        'Peking duck reunion dinner',
        'Hutongs rickshaw tour',
      ],
      notes: 'Reunited! Explore Beijing\'s winter wonders together — fewer crowds, magical snow scenes.',
    },
    {
      id: 'nanjing-suzhou',
      name: 'Nanjing/Suzhou · 南京/苏州',
      emoji: '🌿',
      coords: [32.0603, 118.7969],
      startDate: '2027-01-04',
      endDate: '2027-01-07',
      nights: 4,
      tags: [{ label: 'Gardens', cls: 'green' }, 'History', 'Canals'],
      image: 'https://images.unsplash.com/photo-1689825650048-55d2216868f7?w=800&q=80',
      weather: { temp: '-2–7°C', season: 'Winter · Jan', icon: '🌤️' },
      transport: { from: 'Beijing', mode: '🚄', duration: '~4h' },
      activities: [
        'Sun Yat-sen Mausoleum (Nanjing)',
        'Confucius Temple & Qinhuai River',
        'Humble Administrator\'s Garden (Suzhou)',
        'Pingjiang Road canal walk',
        'Tea house experience',
      ],
      notes: 'Classical gardens, ancient capitals, and canal-side charm.',
    },
    {
      id: 'shanghai',
      name: 'Shanghai · 上海',
      emoji: '🌃',
      coords: [31.2304, 121.4737],
      startDate: '2027-01-08',
      endDate: '2027-01-11',
      nights: 3,
      tags: ['Modern', { label: 'Nightlife', cls: 'amber' }, 'Shopping'],
      image: 'https://images.unsplash.com/photo-1506158669146-619067262a00?w=800&q=80',
      weather: { temp: '1–9°C', season: 'Winter · Jan', icon: '🌤️' },
      transport: { from: 'Nanjing/Suzhou', mode: '🚄', duration: '~1h' },
      activities: [
        'The Bund skyline walk',
        'Huangpu River night cruise',
        'Yu Garden & Old Town',
        'Nanjing Road shopping',
        'French Concession café stroll',
      ],
      notes: 'End the journey in style — a final night on the Bund before flying home.',
    },
  ],

  thailandCities: [
    {
      name: 'Bangkok',
      nights: 6,
      highlights: 'Grand Palace, street food, Chatuchak Market, Ayutthaya',
    },
  ],

  transport: [
    { from: 'Hong Kong', to: 'Shenzhen', mode: '🛬', duration: 'Arrival' },
    { from: 'Shenzhen', to: 'Wangxian Valley', mode: '✈️', duration: '~2h' },
    { from: 'Wangxian Valley', to: 'Chongqing', mode: '🚌', duration: '~3h' },
    { from: 'Chongqing', to: 'Chengdu', mode: '🚄', duration: '~3h' },
    { from: 'Chengdu (split)', to: 'Dalian / Thailand', mode: '✈️', duration: '~3h' },
    { from: 'Dalian / Thailand', to: 'Beijing (reunite)', mode: '✈️', duration: '~2h / ~5h' },
    { from: 'Beijing', to: 'Nanjing/Suzhou', mode: '🚄', duration: '~4h' },
    { from: 'Nanjing/Suzhou', to: 'Shanghai', mode: '🚄', duration: '~1h' },
    { from: 'Shanghai', to: 'Auckland', mode: '🛫', duration: 'Departure' },
  ],

  budget: {
    currency: 'NZD',
    categories: [
      {
        name: '✈️ Transport',
        estimatedMin: 350,
        estimatedMax: 700,
        unit: 'total',
        note: 'All flights between cities plus high-speed trains. Booking early saves a lot.',
      },
      {
        name: '🏨 Hotels',
        estimatedMin: 45,
        estimatedMax: 90,
        unit: '/ night',
        note: 'Beijing, Shanghai & Shenzhen are pricier ($60–90). Smaller cities more affordable.',
      },
      {
        name: '🍜 Food & Activities',
        estimatedMin: 20,
        estimatedMax: 40,
        unit: '/ day',
        note: 'Street food and local restaurants are cheap ($5–15). Nice dinners add up.',
      },
      {
        name: '🚕 City Transport',
        estimatedMin: 5,
        estimatedMax: 15,
        unit: '/ day',
        note: 'Metro is very affordable. Didi rides start around $3–$8.',
      },
      {
        name: '🎟️ Attractions',
        estimatedMin: 10,
        estimatedMax: 40,
        unit: '/ site',
        note: 'Budget ~$100–$200 total for all major sites.',
      },
      {
        name: '📱 Extras',
        estimatedMin: 50,
        estimatedMax: 150,
        unit: 'total',
        note: 'VPN, SIM / eSIM, travel insurance, laundry, souvenirs.',
      },
    ],
    totalMin: 2200,
    totalMax: 4000,
    totalNote: 'For the entire China portion (~44 nights). Thailand is additional.',
  },

  packing: {
    categories: [
      {
        name: '📄 Documents',
        items: ['Passport', 'Visa documents', 'Flight tickets (print + digital)', 'Hotel booking confirmations', 'Travel insurance', 'Vaccination card', 'Driver\'s license'],
      },
      {
        name: '👕 Clothing',
        items: ['T-shirts (5x)', 'Long pants (2x)', 'Underwear (7x)', 'Socks (7x)', 'Jacket / hoodie', 'Swimwear', 'Comfortable walking shoes', 'Rain jacket'],
      },
      {
        name: '🧴 Toiletries',
        items: ['Toothbrush & toothpaste', 'Shampoo & conditioner', 'Sunscreen', 'Deodorant', 'Razor', 'First aid kit', 'Prescription medication'],
      },
      {
        name: '🔌 Electronics',
        items: ['Phone charger', 'Travel adapter (Type A + I)', 'Power bank', 'Headphones', 'Camera', 'VPN set up before departure'],
      },
      {
        name: '💰 Finances',
        items: ['Credit card (no foreign fee)', 'Debit card', 'Some cash (CNY)', 'Alipay set up', 'WeChat Pay set up'],
      },
      {
        name: '📱 Apps to Install',
        items: ['Alipay', 'WeChat', 'Didi (ride-hailing)', 'Metro apps per city', 'Google Maps offline', 'Maps.me', 'Translate app'],
      },
    ],
  },

  tips: [
    'HK→SZ is seamless — take the MTR East Rail to Futian or the high-speed rail',
    'Split on Dec 24: book Dalian & Bangkok flights from Chengdu in advance',
    'Beijing in winter is cold (-8°C) but spectacular — pack thermal layers',
    'Download Alipay and WeChat Pay before arrival',
    'Get a VPN set up before arriving in China',
    'Nanjing → Suzhou → Shanghai by high-speed rail is the smoothest final leg',
    'Book the Shanghai→Auckland flight well ahead — Jan 11 is peak return season',
  ],
};

// Get a city by its id
function getCity(id) {
  return TRIP.cities.find(c => c.id === id);
}

// Get total nights in China
function totalChinaNights() {
  return TRIP.cities.reduce((sum, c) => sum + c.nights, 0);
}
